<?xml version="1.0"?>
<robot name="sensor_gps_with_mast" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:property name="mast_height" value="0.5" />
  <xacro:property name="mast_radius" value="0.010" />

  <!-- if no latitude/longitud is specified, then use Fuente del Jarro as default -->
  <xacro:macro name="sensor_gps_with_mast" params="prefix parent *origin gps_latitude:=^|39.5080331 gps_longitude:=^|-0.4619816 update_rate:=^|5">

	  <!-- MAST OF THE ANTENNA GPS -->
	  <joint name="${prefix}_joint" type="fixed">
	    <axis xyz="0 1 0"/>
	    <xacro:insert_block name="origin"/>
	    <parent link="${parent}"/>
	    <child link="${prefix}_mast_base_link"/>
	  </joint>

	  <link name="${prefix}_mast_base_link">
		<inertial>
			<origin xyz="0.0 0 0.0" rpy="0 0 0" />
			<mass value="1.0" />
			<xacro:solid_cuboid_inertia m="1.0" w="${mast_radius}" h="${mast_radius}" d="${mast_height}" />
		</inertial>
	    <visual>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
	      <material name="mast_color">
            <color rgba="0.1 0.1 0.1 1"/>
          </material>
	      <geometry>
	        <cylinder length="${mast_height}" radius="${mast_radius}" />
	      </geometry>
	    </visual>
	    <collision>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
	      <geometry>
	        <cylinder length="${mast_height}" radius="${mast_radius}" />
	      </geometry>
	    </collision>
	  </link>

	  <joint name="${prefix}_mast_joint" type="fixed">
	    <axis xyz="0 1 0"/>
	    <parent link="${prefix}_mast_base_link"/>
	    <child link="${prefix}_base_link"/>
	    <origin xyz="0 0 ${mast_height/2.0}" rpy="0 0 0" />
	  </joint>

	  <gazebo reference="${prefix}_mast_base_link">
	    <material>Gazebo/Black</material>
	    <gravity>true</gravity>
	  </gazebo>

      <!-- ANTENNA GPS -->
	  <link name="${prefix}_base_link">
	    <inertial>
			<origin xyz="0.0 0 0.015" rpy="0 0 0" />
			<mass value="0.2" />
			<xacro:solid_cuboid_inertia m="0.2" w="0.081" h="0.081" d="0.03" />
      	</inertial>
	    <visual>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
	      <material name="gps_color">
           <color rgba="1 1 1 1"/>
        </material>
	      <geometry>
	        <mesh filename="package://gaitech_sensors/meshes/antenna_3GO16.stl" scale="1.0 1.0 1.0"/>
	      </geometry>
	    </visual>
	    <collision>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
	      <geometry>
	        <mesh filename="package://gaitech_sensors/meshes/antenna_3GO16.stl" scale="1.0 1.0 1.0"/>
	      </geometry>
	    </collision>
	  </link>


	  <gazebo reference="${prefix}_base_link">
	    <material>Gazebo/White</material>
	    <gravity>true</gravity>
	  </gazebo>

    <gazebo>
      <plugin name="${prefix}_controller" filename="libhector_gazebo_ros_gps.so">
        <alwaysOn>1</alwaysOn>
        <updateRate>${update_rate}</updateRate>
        <bodyName>${prefix}_base_link</bodyName> <!-- must be the link of the gps device, not the base_link or base_footprint -->
        <frameId>${prefix}_base_link</frameId>   <!-- which frame_id would be on the published message -->
        <topicName>gps/fix</topicName>
        <!-- GPS coordinates -->
        <referenceLatitude>${gps_latitude}</referenceLatitude>
        <referenceLongitude>${gps_longitude}</referenceLongitude>
        <!-- To set heading in ENU orientation (degrees) -->
        <referenceHeading>90</referenceHeading>
        <velocityTopicName>gps/fix_velocity</velocityTopicName>
        <drift>0.0 0.0 0.0</drift>
        <!--<drift>0.0001 0.0001 0.0001</drift>-->
        <!--<drift>0.3 0.3 0.3</drift>-->
        <gaussianNoise>0.00001 0.00001 0.00001</gaussianNoise>
        <!--<gaussianNoise>0.00001 0.00001 0.00001</gaussianNoise>-->
        <velocityDrift>0.00001 0.00001 0.00001</velocityDrift>
        <!--<velocityGaussianNoise>0.1 0.1 0.1</velocityGaussianNoise>-->
        <velocityGaussianNoise>0.00001 0.00001 0.00001</velocityGaussianNoise>

      </plugin>
	</gazebo>

  </xacro:macro>

</robot>
